CREATE SEQUENCE MEMBER_ID_SEQ;

CREATE TABLE MEMEBER (
 MEMBER_ID NUMBER(10) CONSTRAINT MMBR_ID_PK PRIMARY KEY,
 NAME VARCHAR2(10) CONSTRAINT MMBR_NM_NN NOT NULL,
 BIRTH DATE,
 GENDER VARCHAR2(10) CONSTRAINT MMBR_GNDR_NN NOT NULL,
 MEMBER_SINCE DATE CONSTRAINT MMBR_MMBRSNC_NN NOT NULL
);

CREATE TABLE PUBLISHER(
 PUBLISHER_ID NUMBER(10) CONSTRAINT PBLSHR_ID_PK PRIMARY KEY,
 NAME VARCHAR2(10) CONSTRAINT PBLSHR_NM_NN NOT NULL,
 CITY VARCHAR2(10) CONSTRAINT PBLSHR_CT_NN NOT NULL,
 ZIP NUMBER(5) CONSTRAINT PBLSHR_ZP_UNQ UNIQUE
);

CREATE TABLE AUTHOR(
 AUTHOR_ID NUMBER(10) CONSTRAINT ATHR_ID_PK PRIMARY KEY,
 NAME VARCHAR2(10) CONSTRAINT ATHR_NM_NN NOT NULL,
 GENDER VARCHAR2(10)CONSTRAINT ATHR_GNDR_NN NOT NULL
);

CREATE TABLE BOOK(
 ISBN VARCHAR2(40) CONSTRAINT BK_ISBN_PK PRIMARY KEY,
 TITLE VARCHAR2(40) CONSTRAINT BK_TTL_NN NOT NULL,
 PUBLISHER_ID NUMBER(10) CONSTRAINT BK_PBLID_FK REFERENCES PUBLISHER(PUBLISHER_ID),
 PUB_DATE DATE CONSTRAINT BK_PBLDT_NN NOT NULL,
 PAGE_NUM NUMBER(10) DEFAULT 1
);

CREATE TABLE BOOK_AUTHOR(
 ISBN VARCHAR2(40) CONSTRAINT BKATHR_ISBN_FK REFERENCES BOOK(ISBN),
 AUTHOR_ID NUMBER(10) CONSTRAINT BKATHR_ATHRID_FK REFERENCES AUTHOR(AUTHOR_ID)
);


CREATE TABLE LOAN(
    ISBN VARCHAR2(40) CONSTRAINT LN_ISBN_FK REFERENCES BOOK(ISBN),
    MEMBER_ID NUMBER(10) CONSTRAINT LN_MMBR_ID_FK REFERENCES MEMBER(MEMBER_ID),
    CHECKOUT_DATE DATE CONSTRAINT LN_CHKOUT_PK PRIMARY KEY,
    DUE_DATE DATE CONSTRAINT LN_DUE_NN NOT NULL,
    FEE NUMBER(10)
);